import type { Exercise, Lesson } from '../domain/types.ts'

type Choice = [
  text: string,
  question: string,
  options: [string, string, string],
  correct: number,
  hint: string,
  explanation: string,
]
type Recall = [question: string, answer: string, hint: string, explanation: string]
type Unit = {
  id: string
  title: string
  goal: string
  topic: Lesson['topic']
  phrase: string
  translation: string
  note: string
  read: Choice
  recall: Recall
  listen: Choice
  review: Recall
  speaking: string
  writing: string
  check: string[]
  checkpoint?: number
}
function choice(id: string, data: Choice, listening = false): Exercise {
  const [text, prompt, options, correct, hint, explanation] = data
  return {
    id,
    kind: 'choice',
    prompt,
    options,
    answers: [options[correct]],
    hint,
    explanation,
    ...(listening ? { audioText: text } : { passage: text }),
  }
}
function recall(id: string, [prompt, answer, hint, explanation]: Recall): Exercise {
  return { id, kind: 'input', prompt, answers: [answer], hint, explanation }
}
const units: Unit[] = [
  {
    id: 'family',
    title: 'Một người trong gia đình',
    topic: 'Đời sống',
    goal: 'Giới thiệu một người bằng she/he và be.',
    phrase: 'This is my sister. She is a student.',
    translation: 'Đây là chị/em gái của mình. Chị/em ấy là học sinh, sinh viên.',
    note: 'Dùng she cho người nữ, he cho người nam khi người đó dùng đại từ này. She/he đi với is trong câu giới thiệu hiện tại.',
    read: [
      'This is my brother, Ben. He is a cook. He likes rice.',
      'Ben làm nghề gì?',
      ['Đầu bếp', 'Giáo viên', 'Sinh viên'],
      0,
      'Tìm từ chỉ nghề sau is.',
      'A cook là đầu bếp; likes rice nói sở thích, không phải nghề.',
    ],
    recall: [
      'Điền một từ: My sister is Mai. ___ is a student.',
      'She',
      'Đại từ thay cho my sister.',
      'She thay cho my sister trong câu này.',
    ],
    listen: [
      'This is my mother. She is a teacher.',
      'Người nói giới thiệu ai?',
      ['Chị/em gái', 'Mẹ', 'Bạn'],
      1,
      'Chú ý từ sau my.',
      'My mother nghĩa là mẹ của mình.',
    ],
    review: [
      'Điền be: My brother ___ a cook.',
      'is',
      'My brother tương ứng với he.',
      'He/my brother đi với is.',
    ],
    speaking: 'Giới thiệu một người thật hoặc tưởng tượng bằng This is … rồi He/She is ….',
    writing: 'Viết hai câu giới thiệu một người, không cần dùng tên thật.',
    check: ['Đã nói người đó là ai.', 'He/She đi với is.'],
  },
  {
    id: 'have',
    title: 'Những thứ mình có',
    topic: 'Đời sống',
    goal: 'Nói có một đồ vật bằng have/has.',
    phrase: 'I have a bike. My friend has a car.',
    translation: 'Mình có một chiếc xe đạp. Bạn mình có một chiếc ô tô.',
    note: 'I/you/we/they dùng have; he/she/it hoặc một người dùng has. Dùng a trước một danh từ đếm được số ít phù hợp.',
    read: [
      'I have a small bag. My sister has a red hat. We walk to school.',
      'Ai có chiếc mũ đỏ?',
      ['Người kể', 'Chị/em gái', 'Cả hai'],
      1,
      'Tìm người đứng trước has a red hat.',
      'My sister has a red hat: chị/em gái có mũ đỏ.',
    ],
    recall: [
      'Điền have hoặc has: My friend ___ a blue pen.',
      'has',
      'My friend là một người.',
      'My friend dùng has.',
    ],
    listen: [
      'I have two books and a pencil. My bag is blue.',
      'Người nói có bao nhiêu quyển sách?',
      ['Một', 'Hai', 'Ba'],
      1,
      'Nghe số đứng trước books.',
      'Two books là hai quyển sách.',
    ],
    review: [
      'Điền have hoặc has: We ___ a new table.',
      'have',
      'We dùng cùng dạng với I.',
      'We dùng have, không dùng has.',
    ],
    speaking: 'Nói một đồ vật mình có và một đồ vật người khác có.',
    writing: 'Viết hai câu với I have và một người + has.',
    check: ['Đã phân biệt have/has theo chủ ngữ.', 'Danh từ số ít có a/an khi cần.'],
  },
  {
    id: 'likes',
    title: 'Điều mình thích',
    topic: 'Giải trí',
    goal: 'Nói sở thích của mình và của một người khác.',
    phrase: 'I like music. My brother likes films.',
    translation: 'Mình thích âm nhạc. Anh/em trai mình thích phim.',
    note: 'Ở hiện tại đơn, I dùng like; he/she hoặc một người dùng likes. Music trong câu này không cần a.',
    read: [
      'Anna likes books. Her brother likes football. They both like music.',
      'Cả hai cùng thích gì?',
      ['Sách', 'Bóng đá', 'Âm nhạc'],
      2,
      'Both nghĩa là cả hai.',
      'They both like music cho biết sở thích chung.',
    ],
    recall: [
      'Điền like hoặc likes: My mother ___ tea.',
      'likes',
      'My mother tương ứng với she.',
      'My mother likes tea: thêm s ở likes.',
    ],
    listen: [
      'I like tea, but I do not like coffee.',
      'Người nói thích đồ uống nào?',
      ['Trà', 'Cà phê', 'Cả hai'],
      0,
      'Chú ý do not ở phần sau.',
      'Người nói thích trà và không thích cà phê.',
    ],
    review: [
      'Điền like hoặc likes: They ___ reading.',
      'like',
      'They không thêm s vào động từ hiện tại đơn.',
      'They like reading là câu đúng.',
    ],
    speaking: 'Nói một điều mình thích; hỏi người bên cạnh hoặc tự đóng vai đáp lại.',
    writing: 'Viết một câu về mình và một câu về sở thích của người khác.',
    check: ['Đã thêm s khi chủ ngữ là một người khác.', 'Câu thể hiện sở thích cụ thể.'],
  },
  {
    id: 'questions',
    title: 'Hỏi một câu để làm quen',
    topic: 'Đời sống',
    goal: 'Dùng Do you …? để hỏi thói quen hoặc sở thích.',
    phrase: 'Do you play tennis? Yes, I do.',
    translation: 'Bạn có chơi quần vợt không? Có.',
    note: 'Với động từ thường, câu hỏi hiện tại đơn có Do you + động từ nguyên dạng. Đáp ngắn Yes, I do hoặc No, I do not.',
    read: [
      'A: Do you like cooking? B: Yes, I do. I cook at home on Sundays.',
      'B nấu ăn ở đâu?',
      ['Ở trường', 'Ở nhà', 'Ở quán'],
      1,
      'Tìm cụm sau cook.',
      'At home là ở nhà.',
    ],
    recall: [
      'Điền trợ động từ: ___ you read books?',
      'Do',
      'Câu hỏi về thói quen với you.',
      'Do you read books? dùng Do trước you.',
    ],
    listen: [
      'Do you play football? No, I do not. I play tennis.',
      'Người trả lời chơi môn nào?',
      ['Bóng đá', 'Quần vợt', 'Bơi'],
      1,
      'Phần sau câu trả lời No nêu môn chơi.',
      'I play tennis cho biết người đó chơi quần vợt.',
    ],
    review: [
      'Điền một từ: Do you like tea? Yes, I ___.',
      'do',
      'Dùng lại trợ động từ trong câu hỏi.',
      'Yes, I do là câu đáp ngắn.',
    ],
    speaking: 'Tự đóng vai hai người: hỏi Do you …? rồi trả lời ngắn.',
    writing: 'Viết một cặp hỏi–đáp về một thói quen.',
    check: ['Câu hỏi bắt đầu bằng Do you.', 'Động từ sau you ở dạng nguyên.', 'Có dấu hỏi.'],
  },
  {
    id: 'negative',
    title: 'Điều mình không làm',
    topic: 'Đời sống',
    goal: 'Dùng do not/don’t để nói một thói quen không có.',
    phrase: 'I do not work on Sundays.',
    translation: 'Mình không làm việc vào Chủ nhật.',
    note: 'I/you/we/they + do not + động từ nguyên dạng. Do not có thể viết gọn là don’t; phần điền từ sẽ nêu rõ dạng cần dùng.',
    read: [
      'I work from Monday to Friday. I do not work on Saturday. On Saturday, I visit my aunt.',
      'Người kể làm gì vào thứ Bảy?',
      ['Đi làm', 'Thăm cô/dì', 'Đi học'],
      1,
      'Phân biệt do not work với visit.',
      'Người kể không đi làm vào thứ Bảy mà thăm cô/dì.',
    ],
    recall: [
      'Điền một từ: I do ___ drink coffee.',
      'not',
      'Từ phủ định đứng sau do.',
      'Do not tạo câu phủ định.',
    ],
    listen: [
      'I do not watch TV in the morning. I listen to music.',
      'Buổi sáng người nói làm gì?',
      ['Xem TV', 'Nghe nhạc', 'Đọc báo'],
      1,
      'Hành động đầu bị phủ định.',
      'Người nói không xem TV; người đó nghe nhạc.',
    ],
    review: [
      'Điền một từ: We ___ not play games at school.',
      'do',
      'We dùng trợ động từ do trong phủ định hiện tại đơn.',
      'We do not play games at school.',
    ],
    speaking: 'Nói một việc mình thường làm và một việc không làm.',
    writing: 'Viết một câu khẳng định và một câu do not về sinh hoạt.',
    check: ['Sau do not là động từ nguyên dạng.', 'Hai câu thể hiện hai ý rõ ràng.'],
  },
  {
    id: 'ability',
    title: 'Mình có thể làm được',
    topic: 'Giải trí',
    goal: 'Dùng can/cannot để nói khả năng.',
    phrase: 'I can swim, but I cannot drive.',
    translation: 'Mình biết bơi nhưng chưa biết lái xe.',
    note: 'Can và cannot đi với động từ nguyên dạng, không thêm to. Cannot viết liền khi dùng dạng đầy đủ.',
    read: [
      'Tom can cook. He cannot swim. His sister can swim and ride a bike.',
      'Tom làm được việc gì?',
      ['Nấu ăn', 'Bơi', 'Không việc nào'],
      0,
      'Chú ý can và cannot.',
      'Tom can cook là Tom biết nấu ăn.',
    ],
    recall: [
      'Điền can hoặc cannot: I know how to swim. I ___ swim.',
      'can',
      'Know how to nghĩa là biết cách làm.',
      'I can swim diễn đạt khả năng bơi.',
    ],
    listen: [
      'I can sing, but I cannot play the piano.',
      'Người nói chưa làm được việc gì?',
      ['Hát', 'Chơi đàn piano', 'Cả hai'],
      1,
      'Nghe phần sau but.',
      'Cannot play the piano nghĩa là chưa biết chơi piano.',
    ],
    review: [
      'Điền động từ swim: She can ___ well.',
      'swim',
      'Sau can dùng dạng nguyên.',
      'She can swim well; không thêm s hay to.',
    ],
    speaking: 'Nói một khả năng và một điều muốn tập thêm.',
    writing: 'Viết hai câu can/cannot. Có thể viết về nhân vật tưởng tượng.',
    check: ['Sau can/cannot không có to.', 'Động từ không thêm s.'],
  },
  {
    id: 'routine',
    title: 'Buổi sáng có thứ tự',
    topic: 'Đời sống',
    goal: 'Nối hai hành động bằng first và then.',
    phrase: 'First, I have breakfast. Then, I go to work.',
    translation: 'Đầu tiên mình ăn sáng. Sau đó mình đi làm.',
    note: 'First mở hành động đầu; then mở hành động sau. Have breakfast thường không dùng a trước breakfast.',
    read: [
      'First, I get up. Then, I have breakfast. I go to school at eight.',
      'Người kể làm gì sau khi thức dậy?',
      ['Đi học', 'Ăn sáng', 'Đi ngủ'],
      1,
      'Tìm hành động đứng ngay sau get up.',
      'Then, I have breakfast nêu hành động kế tiếp.',
    ],
    recall: [
      'Điền từ chỉ “sau đó”: First, I eat. ___, I study.',
      'Then',
      'Từ nối chỉ bước tiếp theo.',
      'Then nối bước tiếp theo trong trình tự.',
    ],
    listen: [
      'First, I wash my face. Then, I have tea. I leave home at seven.',
      'Trước khi uống trà, người nói làm gì?',
      ['Rời nhà', 'Rửa mặt', 'Ăn trưa'],
      1,
      'Nghe hành động sau First.',
      'First, I wash my face là rửa mặt trước.',
    ],
    review: [
      'Điền từ chỉ “đầu tiên”: ___, I read. Then, I write.',
      'First',
      'Từ mở đầu một trình tự.',
      'First giới thiệu bước đầu.',
    ],
    speaking: 'Kể hai bước trong buổi sáng bằng First và Then.',
    writing: 'Viết hai hoặc ba câu theo trình tự một buổi sáng.',
    check: ['Thứ tự hành động rõ ràng.', 'Mỗi câu có chủ ngữ và động từ.'],
  },
  {
    id: 'plural',
    title: 'Từ một đến nhiều đồ vật',
    topic: 'Đời sống',
    goal: 'Dùng there are với nhiều đồ vật.',
    phrase: 'There are three chairs in the room.',
    translation: 'Có ba chiếc ghế trong phòng.',
    note: 'There is đi với một vật; there are đi với nhiều vật. Chair → chairs, book → books; không phải mọi danh từ đều chỉ thêm s.',
    read: [
      'There is a table in my room. There are two chairs and four books.',
      'Có bao nhiêu chiếc ghế?',
      ['Một', 'Hai', 'Bốn'],
      1,
      'Chú ý số ngay trước chairs.',
      'Two chairs nghĩa là hai chiếc ghế.',
    ],
    recall: [
      'Điền is hoặc are: There ___ two cups on the table.',
      'are',
      'Two cups là nhiều hơn một.',
      'There are đi với danh từ số nhiều.',
    ],
    listen: [
      'There are five students and one teacher in the room.',
      'Có bao nhiêu giáo viên?',
      ['Một', 'Năm', 'Sáu'],
      0,
      'Phân biệt students và teacher.',
      'One teacher là một giáo viên.',
    ],
    review: [
      'Điền is hoặc are: There ___ a pen in my bag.',
      'is',
      'A pen là một chiếc bút.',
      'There is đi với a pen số ít.',
    ],
    speaking: 'Nhìn quanh, nói một câu There is và một câu There are.',
    writing: 'Mô tả hai nhóm đồ vật bằng hai câu.',
    check: ['Is/are phù hợp số lượng.', 'Danh từ số nhiều có dạng đúng.'],
  },
  {
    id: 'places',
    title: 'Chiếc chìa khóa ở đâu?',
    topic: 'Đời sống',
    goal: 'Phân biệt in, on và under khi nói vị trí.',
    phrase: 'My keys are under the chair.',
    translation: 'Chìa khóa của mình ở dưới ghế.',
    note: 'In: ở trong; on: ở trên bề mặt; under: ở dưới. Keys là số nhiều nên dùng are.',
    read: [
      'My bag is on the chair. My phone is in the bag. My shoes are under the chair.',
      'Điện thoại ở đâu?',
      ['Trong túi', 'Dưới ghế', 'Trên bàn'],
      0,
      'Tìm câu có my phone.',
      'My phone is in the bag nghĩa là điện thoại trong túi.',
    ],
    recall: [
      'Điền từ chỉ “ở dưới”: The cat is ___ the table.',
      'under',
      'Chọn in, on hoặc under.',
      'Under diễn đạt vị trí bên dưới.',
    ],
    listen: [
      'The book is on the desk. The pen is under the desk.',
      'Chiếc bút ở đâu?',
      ['Trên bàn', 'Dưới bàn', 'Trong túi'],
      1,
      'Nghe câu thứ hai về the pen.',
      'The pen is under the desk: bút ở dưới bàn.',
    ],
    review: [
      'Điền từ chỉ “ở trong”: My phone is ___ my bag.',
      'in',
      'Từ chỉ một vật nằm bên trong.',
      'In my bag là ở trong túi mình.',
    ],
    speaking: 'Đặt một đồ vật ở hai vị trí rồi tự nói vị trí mỗi lần.',
    writing: 'Viết hai câu giúp người khác tìm đồ vật.',
    check: ['Đã nêu đồ vật và vị trí.', 'In/on/under đúng ý định.'],
  },
  {
    id: 'directions',
    title: 'Một chỉ dẫn thật ngắn',
    topic: 'Đời sống',
    goal: 'Hiểu go straight, turn left và turn right.',
    phrase: 'Go straight and turn left at the bank.',
    translation: 'Đi thẳng rồi rẽ trái ở ngân hàng.',
    note: 'Lời chỉ dẫn dùng động từ nguyên dạng ở đầu câu: Go…, Turn…. Left là trái; right là phải.',
    read: [
      'Go straight. Turn right at the park. The cafe is next to the bank.',
      'Cần rẽ ở đâu?',
      ['Công viên', 'Quán cà phê', 'Trường học'],
      0,
      'Tìm nơi đứng sau at trong chỉ dẫn Turn.',
      'Turn right at the park là rẽ phải ở công viên.',
    ],
    recall: [
      'Điền từ chỉ “trái”: Turn ___ at the school.',
      'left',
      'Trái là left, phải là right.',
      'Turn left là rẽ trái.',
    ],
    listen: [
      'Go straight and turn right at the school.',
      'Nghe chỉ dẫn: rẽ hướng nào?',
      ['Trái', 'Phải', 'Quay lại'],
      1,
      'Chú ý từ sau turn.',
      'Turn right nghĩa là rẽ phải.',
    ],
    review: [
      'Điền từ chỉ “phải”: Turn ___ at the bank.',
      'right',
      'Từ đối lập với left.',
      'Turn right là rẽ phải.',
    ],
    speaking: 'Vẽ một đường đơn giản trên giấy rồi nói hai chỉ dẫn.',
    writing: 'Viết hai chỉ dẫn cho đường tưởng tượng, không cần địa chỉ thật.',
    check: ['Mỗi chỉ dẫn bắt đầu bằng động từ.', 'Đã phân biệt left/right.'],
  },
  {
    id: 'shopping',
    title: 'Mua một vài món nhỏ',
    topic: 'Ăn uống',
    goal: 'Phân biệt a với some trong ví dụ mua đồ.',
    phrase: 'I need an apple and some water.',
    translation: 'Mình cần một quả táo và một ít nước.',
    note: 'Apple đếm được: an apple. Water dùng như chất lỏng không đếm từng vật trong câu này: some water. A/an phụ thuộc âm đầu của từ tiếp theo.',
    read: [
      'We need two bananas, some rice and a bottle of water. We have apples at home.',
      'Món nào đã có ở nhà?',
      ['Chuối', 'Táo', 'Gạo'],
      1,
      'Tìm câu có at home.',
      'We have apples at home: đã có táo ở nhà.',
    ],
    recall: [
      'Điền a hoặc an: I want ___ orange.',
      'an',
      'Orange bắt đầu bằng một nguyên âm khi nói.',
      'Dùng an trước orange.',
    ],
    listen: [
      'Please buy some bread and two apples. We have milk.',
      'Cần mua bao nhiêu quả táo?',
      ['Một', 'Hai', 'Ba'],
      1,
      'Nghe số trước apples.',
      'Two apples là hai quả táo.',
    ],
    review: [
      'Điền some hoặc an: I need ___ rice.',
      'some',
      'Rice trong câu này là danh từ không đếm được.',
      'Some rice là một ít gạo/cơm tùy ngữ cảnh.',
    ],
    speaking: 'Nói danh sách ba món muốn mua, dùng a/an/some phù hợp.',
    writing: 'Viết lời nhắn mua hai món, có một món dùng some.',
    check: ['Không dùng a/an trực tiếp với water/rice.', 'Số lượng hoặc lượng được diễn đạt rõ.'],
  },
  {
    id: 'prices',
    title: 'Hỏi giá và nghe con số',
    topic: 'Ăn uống',
    goal: 'Hỏi giá bằng How much và nghe giá ngắn.',
    phrase: 'How much is this cup? It is five dollars.',
    translation: 'Chiếc cốc này giá bao nhiêu? Giá năm đô la.',
    note: 'How much is this …? hỏi giá một món. Số và tiền trong bài chỉ là tình huống luyện tập, không phải giá thực tế.',
    read: [
      'A cup is four dollars. A plate is six dollars. A spoon is two dollars.',
      'Chiếc đĩa giá bao nhiêu?',
      ['Hai đô la', 'Bốn đô la', 'Sáu đô la'],
      2,
      'Plate là chiếc đĩa.',
      'A plate is six dollars cho biết giá chiếc đĩa.',
    ],
    recall: [
      'Điền một từ: How ___ is this bag?',
      'much',
      'Cụm hỏi giá là How much.',
      'How much is this bag? hỏi giá chiếc túi.',
    ],
    listen: [
      'This sandwich is seven dollars. The tea is three dollars.',
      'Trà giá bao nhiêu trong bài nghe?',
      ['Ba đô la', 'Bảy đô la', 'Mười đô la'],
      0,
      'Nghe giá sau The tea.',
      'The tea is three dollars: trà giá ba đô la.',
    ],
    review: [
      'Điền is hoặc are: How much ___ this book?',
      'is',
      'This book là một quyển sách.',
      'How much is this book? dùng is.',
    ],
    speaking: 'Đóng vai người mua và bán: hỏi giá một món rồi trả lời bằng giá tự chọn.',
    writing: 'Viết một cặp hỏi–đáp giá, dùng số nhỏ mình đã biết.',
    check: ['Câu hỏi có How much.', 'Đơn vị tiền xuất hiện trong câu đáp.'],
  },
  {
    id: 'schedule',
    title: 'Ngày nào, lúc mấy giờ?',
    topic: 'Học tập',
    goal: 'Dùng on với ngày và at với giờ.',
    phrase: 'My class starts at nine on Monday.',
    translation: 'Lớp của mình bắt đầu lúc chín giờ vào thứ Hai.',
    note: 'At đi với giờ cụ thể; on đi với thứ/ngày. Monday viết hoa chữ đầu.',
    read: [
      'The English class is on Tuesday at ten. The music class is on Friday at two.',
      'Lớp tiếng Anh vào thứ mấy?',
      ['Thứ Hai', 'Thứ Ba', 'Thứ Sáu'],
      1,
      'Tuesday là thứ Ba.',
      'The English class is on Tuesday.',
    ],
    recall: [
      'Điền at hoặc on: We meet ___ Friday.',
      'on',
      'Friday là thứ trong tuần.',
      'On Friday: vào thứ Sáu.',
    ],
    listen: [
      'The class starts at eight on Thursday.',
      'Lớp bắt đầu lúc mấy giờ?',
      ['Tám giờ', 'Chín giờ', 'Mười giờ'],
      0,
      'Nghe số sau at.',
      'At eight nghĩa là lúc tám giờ.',
    ],
    review: [
      'Điền at hoặc on: The lesson starts ___ six.',
      'at',
      'Six ở đây là giờ cụ thể.',
      'At six: lúc sáu giờ.',
    ],
    speaking: 'Nói lịch một buổi học tưởng tượng gồm thứ và giờ.',
    writing: 'Viết lời hẹn ngắn có ngày và giờ.',
    check: ['At đi với giờ, on đi với thứ.', 'Tên thứ viết hoa.'],
  },
  {
    id: 'requests',
    title: 'Nhờ giúp và hỏi lại',
    topic: 'Học tập',
    goal: 'Dùng Can you …, please? và lời nhờ nói lại.',
    phrase: 'Can you say that again, please?',
    translation: 'Bạn có thể nói lại điều đó được không?',
    note: 'Can you + động từ nguyên dạng + please? dùng để nhờ. Đây là một cách hữu ích khi chưa nghe rõ; có thể hỏi lại.',
    read: [
      'A: Can you help me, please? B: Yes. A: I cannot find my book.',
      'A cần giúp việc gì?',
      ['Tìm sách', 'Mua đồ ăn', 'Mở cửa'],
      0,
      'Tìm câu nói về vấn đề sau lời nhờ.',
      'I cannot find my book: chưa tìm được sách.',
    ],
    recall: [
      'Điền một từ: Can you help me, ___?',
      'please',
      'Từ dùng để lời nhờ lịch sự hơn.',
      'Please dùng trong lời nhờ lịch sự.',
    ],
    listen: [
      'Can you open the window, please?',
      'Người nói nhờ mở gì?',
      ['Cửa ra vào', 'Cửa sổ', 'Quyển sách'],
      1,
      'Window là cửa sổ.',
      'Open the window nghĩa là mở cửa sổ.',
    ],
    review: [
      'Điền động từ say: Can you ___ that again?',
      'say',
      'Sau can dùng dạng nguyên.',
      'Can you say that again? là lời nhờ nói lại.',
    ],
    speaking: 'Tập một câu nhờ giúp và một câu nhờ nói lại, theo tốc độ thoải mái.',
    writing: 'Viết một lời nhờ cụ thể với Can you và please.',
    check: ['Sau can là động từ nguyên dạng.', 'Có nêu rõ việc cần giúp.'],
  },
  {
    id: 'past-be',
    title: 'Mình đã ở đâu hôm qua?',
    topic: 'Đời sống',
    goal: 'Dùng was/were để nói vị trí trong quá khứ.',
    phrase: 'I was at home yesterday. My friends were at the park.',
    translation: 'Hôm qua mình ở nhà. Các bạn mình ở công viên.',
    note: 'I/he/she/it dùng was; you/we/they dùng were trong quá khứ của be.',
    read: [
      'Yesterday, I was at the library. My sister was at home. My parents were at work.',
      'Người kể ở đâu hôm qua?',
      ['Thư viện', 'Nhà', 'Công viên'],
      0,
      'Tìm câu có I.',
      'I was at the library: người kể ở thư viện.',
    ],
    recall: [
      'Điền was hoặc were: We ___ at school yesterday.',
      'were',
      'We dùng were.',
      'We were at school yesterday.',
    ],
    listen: [
      'I was at the cafe yesterday. My brother was at home.',
      'Anh/em trai ở đâu?',
      ['Quán cà phê', 'Nhà', 'Trường'],
      1,
      'Nghe câu về my brother.',
      'My brother was at home: anh/em trai ở nhà.',
    ],
    review: [
      'Điền was hoặc were: She ___ at the park yesterday.',
      'was',
      'She dùng was.',
      'She was at the park yesterday.',
    ],
    speaking: 'Nói mình và một người khác đã ở đâu hôm qua; có thể tưởng tượng.',
    writing: 'Viết hai câu was/were về hôm qua.',
    check: ['Was/were phù hợp chủ ngữ.', 'Có ngữ cảnh quá khứ rõ ràng.'],
  },
  {
    id: 'past-actions',
    title: 'Một việc đã làm',
    topic: 'Giải trí',
    goal: 'Kể một việc đã xong với động từ quá khứ quen thuộc.',
    phrase: 'I watched a film and cooked dinner yesterday.',
    translation: 'Hôm qua mình xem phim và nấu bữa tối.',
    note: 'Watch → watched, cook → cooked là động từ có quy tắc. Go → went trong bài cũ là bất quy tắc; không thêm ed cho mọi động từ.',
    read: [
      'On Sunday, I visited my friend. We played chess. Then, we cooked lunch.',
      'Hai người chơi gì?',
      ['Bóng đá', 'Cờ vua', 'Quần vợt'],
      1,
      'Tìm từ sau played.',
      'Played chess là đã chơi cờ vua.',
    ],
    recall: [
      'Viết quá khứ của watch: Yesterday, I ___ TV.',
      'watched',
      'Watch là động từ có quy tắc, thêm ed.',
      'Watch → watched.',
    ],
    listen: [
      'Yesterday, I cleaned my room and visited my aunt.',
      'Ngoài dọn phòng, người nói còn làm gì?',
      ['Thăm cô/dì', 'Xem phim', 'Nấu ăn'],
      0,
      'Nghe động từ visited và người đi sau.',
      'Visited my aunt: đã thăm cô/dì.',
    ],
    review: [
      'Viết quá khứ của cook: We ___ dinner yesterday.',
      'cooked',
      'Cook thêm ed ở quá khứ.',
      'Cook → cooked.',
    ],
    speaking: 'Kể hai việc đã làm bằng watched/cooked/visited/played.',
    writing: 'Viết hai câu về một ngày đã qua, có dấu hiệu thời gian.',
    check: ['Động từ đã chuyển sang quá khứ.', 'Không thêm ed vào went.'],
  },
  {
    id: 'past-negative',
    title: 'Một việc đã không làm',
    topic: 'Đời sống',
    goal: 'Dùng did not với động từ nguyên dạng.',
    phrase: 'I did not go to the park yesterday.',
    translation: 'Hôm qua mình không đến công viên.',
    note: 'Sau did not, động từ trở về dạng nguyên: go, không phải went. Did not có dạng viết gọn didn’t.',
    read: [
      'I did not cook dinner yesterday. I had dinner with my cousin at a cafe.',
      'Người kể ăn tối với ai?',
      ['Anh/chị/em họ', 'Giáo viên', 'Một mình'],
      0,
      'Cousin là anh/chị/em họ.',
      'Had dinner with my cousin: ăn tối với anh/chị/em họ.',
    ],
    recall: [
      'Điền go hoặc went: I did not ___ to school yesterday.',
      'go',
      'Sau did not dùng dạng nguyên.',
      'Did not go là đúng; không dùng did not went.',
    ],
    listen: [
      'I did not play tennis yesterday. I stayed at home.',
      'Người nói đã ở đâu?',
      ['Sân tennis', 'Nhà', 'Trường'],
      1,
      'Nghe phần sau câu phủ định.',
      'I stayed at home: người nói đã ở nhà.',
    ],
    review: [
      'Điền một từ: We did ___ watch TV last night.',
      'not',
      'Từ tạo phủ định sau did.',
      'Did not watch TV diễn đạt việc không xem TV.',
    ],
    speaking: 'Kể một việc đã làm và một việc đã không làm hôm qua.',
    writing: 'Viết hai câu, trong đó có did not + động từ.',
    check: [
      'Sau did not dùng động từ nguyên dạng.',
      'Không đổi mọi động từ thành quá khứ sau did.',
    ],
  },
  {
    id: 'future-plans',
    title: 'Kế hoạch ngày mai',
    topic: 'Học tập',
    goal: 'Mở rộng be going to theo chủ ngữ.',
    phrase: 'We are going to study at the library tomorrow.',
    translation: 'Ngày mai chúng mình dự định học ở thư viện.',
    note: 'I am, he/she is, we/you/they are + going to + động từ nguyên dạng. Đây là một cách nói kế hoạch.',
    read: [
      'On Saturday, I am going to visit my grandmother. On Sunday, I am going to study at home.',
      'Người kể định làm gì vào Chủ nhật?',
      ['Thăm bà', 'Học ở nhà', 'Đi làm'],
      1,
      'Tìm câu bắt đầu bằng On Sunday.',
      'On Sunday … study at home: Chủ nhật học ở nhà.',
    ],
    recall: [
      'Điền am, is hoặc are: They ___ going to cook tonight.',
      'are',
      'They đi với are.',
      'They are going to cook tonight.',
    ],
    listen: [
      'We are going to meet at the library tomorrow morning.',
      'Nhóm định gặp ở đâu?',
      ['Công viên', 'Thư viện', 'Nhà hàng'],
      1,
      'Nghe nơi sau meet at.',
      'Meet at the library: gặp ở thư viện.',
    ],
    review: [
      'Điền một từ: She is going ___ read tonight.',
      'to',
      'Mẫu là be going to + động từ.',
      'Going to read nói dự định đọc.',
    ],
    speaking: 'Nói một kế hoạch của mình và một kế hoạch của nhóm tưởng tượng.',
    writing: 'Viết hai câu dự định, có thời gian hoặc địa điểm.',
    check: ['Am/is/are phù hợp chủ ngữ.', 'Sau going to dùng động từ nguyên dạng.'],
  },
  {
    id: 'reasons',
    title: 'Thêm một lý do ngắn',
    topic: 'Học tập',
    goal: 'Nối một ý với lý do bằng because.',
    phrase: 'I study English because I want to travel.',
    translation: 'Mình học tiếng Anh vì muốn đi du lịch.',
    note: 'Because nối lý do với ý chính. Ở bài này hãy dùng một ý chính + because + một câu có chủ ngữ và động từ.',
    read: [
      'I walk to school because it is near my home. My friend takes the bus because her home is far away.',
      'Vì sao người kể đi bộ?',
      ['Nhà ở gần', 'Thích xe buýt', 'Trường đóng cửa'],
      0,
      'Tìm lý do trong câu có I.',
      'Because it is near my home: vì trường gần nhà.',
    ],
    recall: [
      'Điền từ chỉ “bởi vì”: I like this book ___ it is funny.',
      'because',
      'Từ nối đưa ra lý do.',
      'Because it is funny giải thích vì sao thích sách.',
    ],
    listen: [
      'I am going to stay at home because I am tired.',
      'Vì sao người nói định ở nhà?',
      ['Trời mưa', 'Mệt', 'Không có sách'],
      1,
      'Nghe lý do sau because.',
      'Because I am tired nghĩa là vì mình mệt.',
    ],
    review: [
      'Điền một từ: We like this cafe ___ the tea is good.',
      'because',
      'Câu sau giải thích lý do.',
      'Because nối ý thích quán với lý do trà ngon.',
    ],
    speaking: 'Nói một sở thích hoặc kế hoạch rồi thêm một lý do bằng because.',
    writing: 'Viết một câu có ý chính và một lý do ngắn.',
    check: ['Sau because có chủ ngữ và động từ.', 'Lý do liên quan trực tiếp đến ý chính.'],
  },
  {
    id: 'messages',
    title: 'Đọc một lời nhắn',
    topic: 'Đời sống',
    goal: 'Tìm người, thời gian và địa điểm trong lời nhắn ngắn.',
    phrase: 'Hi Ben, can we meet at the cafe at three? See you soon.',
    translation: 'Chào Ben, mình gặp nhau ở quán cà phê lúc ba giờ được không? Hẹn sớm gặp bạn.',
    note: 'Đọc lời nhắn theo ba câu hỏi: ai, ở đâu, lúc nào. Không suy thêm thông tin mà lời nhắn chưa nói.',
    read: [
      'Hi Sam, our class is at ten on Tuesday. Please bring your book. See you at the library. Jo',
      'Cần mang theo gì?',
      ['Vé', 'Sách', 'Đồ ăn'],
      1,
      'Tìm câu bắt đầu bằng Please bring.',
      'Please bring your book: hãy mang sách.',
    ],
    recall: [
      'Điền giới từ: Meet me ___ the cafe at four.',
      'at',
      'At dùng cho điểm hẹn trong câu này.',
      'Meet me at the cafe là gặp mình ở quán cà phê.',
    ],
    listen: [
      'Hi Anna. Please meet me at the park at six. Bring some water.',
      'Người nhận cần đến lúc mấy giờ?',
      ['Bốn giờ', 'Năm giờ', 'Sáu giờ'],
      2,
      'Phân biệt nơi park và giờ six.',
      'At six: lúc sáu giờ.',
    ],
    review: [
      'Điền từ lịch sự: ___ bring your book.',
      'Please',
      'Lời nhờ mở bằng Please.',
      'Please bring your book là lời nhờ mang sách.',
    ],
    speaking: 'Nhờ một người gặp mình, nêu rõ nơi và giờ; tự đọc lại xem có thiếu ý không.',
    writing: 'Viết lời nhắn hai hoặc ba câu: chào, hẹn nơi/giờ, một điều cần mang.',
    check: [
      'Có địa điểm và giờ rõ.',
      'Lời nhắn lịch sự, dễ hiểu.',
      'Không cần dùng tên hoặc địa chỉ thật.',
    ],
  },
  {
    id: 'small-story',
    title: 'Kể một chuyện có đầu cuối',
    topic: 'Giải trí',
    goal: 'Ghép vài câu đã biết thành chuyện ngắn.',
    phrase: 'Yesterday, I visited my friend. We cooked lunch. It was fun.',
    translation: 'Hôm qua mình thăm bạn. Chúng mình nấu bữa trưa. Rất vui.',
    note: 'Kể chuyện ngắn bằng thời gian, việc đã làm và một nhận xét. Dùng từ đã biết; không cần thêm từ khó để câu có giá trị.',
    read: [
      'Yesterday, Mia went to the park with her sister. They played a game. Then, they went home because it was cold.',
      'Vì sao họ về nhà?',
      ['Trời lạnh', 'Họ đi làm', 'Họ không thích công viên'],
      0,
      'Chỉ dùng lý do được nêu sau because.',
      'Because it was cold: vì trời lạnh.',
    ],
    recall: [
      'Điền was hoặc were: Yesterday, the game ___ fun.',
      'was',
      'The game là số ít.',
      'The game was fun nói trò chơi hôm qua vui.',
    ],
    listen: [
      'Yesterday, I went to the library. I read a book. Then, I had lunch with my friend.',
      'Người nói đến đâu trước bữa trưa?',
      ['Thư viện', 'Công viên', 'Rạp phim'],
      0,
      'Nghe nơi ở câu đầu.',
      'Người nói đến thư viện rồi mới ăn trưa.',
    ],
    review: [
      'Viết quá khứ của go: Last Sunday, we ___ to the park.',
      'went',
      'Go là động từ bất quy tắc đã học.',
      'Go → went, không phải goed.',
    ],
    speaking: 'Kể ba câu về hôm qua hoặc một ngày tưởng tượng: ở đâu, làm gì, cảm thấy thế nào.',
    writing: 'Viết ba câu chuyện ngắn. Đọc lại rồi tự sửa một chỗ nếu cần.',
    check: [
      'Có mốc thời gian.',
      'Các động từ phù hợp quá khứ.',
      'Người đọc hiểu thứ tự và ý chính.',
    ],
  },
]

const checkpoints: Unit[] = [
  {
    id: 'week-1-check',
    checkpoint: 1,
    title: 'Nhìn lại tuần 1',
    topic: 'Học tập',
    goal: 'Dùng lại câu giới thiệu, vị trí và giờ trong ngữ cảnh mới.',
    phrase: 'Take your time. Read, listen and try your own sentence.',
    translation: 'Cứ theo nhịp mình. Đọc, nghe và thử câu của riêng bạn.',
    note: 'Đây là bài kiểm tra luyện tập ba câu đóng và phần tự nói/viết. Có thể dùng gợi ý; kết quả không là band IELTS hoặc đánh giá trình độ.',
    read: [
      'My name is Alex. I get up at six. There is a book on my desk.',
      'Alex thức dậy lúc mấy giờ?',
      ['Sáu', 'Bảy', 'Tám'],
      0,
      'Tìm cụm get up at.',
      'Alex gets up at six: Alex thức dậy lúc sáu giờ.',
    ],
    recall: [
      'Điền một từ để gọi đồ uống: I would ___ a cup of tea, please.',
      'like',
      'I would like là dạng đầy đủ của I’d like.',
      'I would like dùng cho lời yêu cầu lịch sự.',
    ],
    listen: [
      'My name is Sam. There is a cup on the table.',
      'Có gì trên bàn?',
      ['Sách', 'Cốc', 'Túi'],
      1,
      'Nghe danh từ sau a.',
      'A cup on the table: một chiếc cốc trên bàn.',
    ],
    review: [
      'Điền một từ: My name ___ Alex.',
      'is',
      'My name là số ít.',
      'My name is Alex là mẫu giới thiệu.',
    ],
    speaking: 'Chào, giới thiệu tên giả và nói giờ thức dậy.',
    writing: 'Viết hai câu giới thiệu và một câu về đồ vật quanh mình.',
    check: ['Câu giới thiệu có My name is.', 'At dùng với giờ.', 'Nêu được vật và vị trí.'],
  },
  {
    id: 'week-2-check',
    checkpoint: 2,
    title: 'Nhìn lại tuần 2',
    topic: 'Học tập',
    goal: 'Đọc thói quen, đặt câu hỏi và nghe một khả năng.',
    phrase: 'Use familiar words to tell us about your day.',
    translation: 'Dùng từ quen thuộc để kể về một ngày của bạn.',
    note: 'Ba câu đóng giúp chọn nội dung cần ôn. Phần nói/viết chỉ có tiêu chí tự xem lại; chưa được chấm bởi giáo viên.',
    read: [
      'Ella has a bike. She likes music. On Sundays, she does not work. She visits her brother.',
      'Ella làm gì vào Chủ nhật?',
      ['Đi làm', 'Thăm anh/em trai', 'Mua xe'],
      1,
      'Đọc cả câu phủ định và câu tiếp theo.',
      'Ella không đi làm; cô ấy thăm anh/em trai.',
    ],
    recall: [
      'Điền trợ động từ: ___ you like cooking?',
      'Do',
      'Câu hỏi hiện tại đơn với you.',
      'Do you like cooking? hỏi sở thích.',
    ],
    listen: [
      'I can cook, but I cannot drive. First, I cook lunch. Then, I read.',
      'Người nói có khả năng nào?',
      ['Lái xe', 'Nấu ăn', 'Bơi'],
      1,
      'Chú ý can và cannot.',
      'I can cook nói khả năng nấu ăn.',
    ],
    review: [
      'Điền have hoặc has: My friend ___ a bike.',
      'has',
      'My friend là một người.',
      'My friend has a bike.',
    ],
    speaking: 'Nói hai thói quen và tự hỏi–đáp một câu Do you …?.',
    writing: 'Viết ba câu về một người, gồm sở thích và một khả năng.',
    check: [
      'Đã phân biệt I like và he/she likes.',
      'Sau can là động từ nguyên dạng.',
      'Câu hỏi có trợ động từ phù hợp.',
    ],
  },
  {
    id: 'week-3-check',
    checkpoint: 3,
    title: 'Nhìn lại tuần 3',
    topic: 'Học tập',
    goal: 'Kết hợp lịch hẹn, số lượng và nghe chỉ dẫn.',
    phrase: 'Check the time, the place and what you need.',
    translation: 'Kiểm tra giờ, nơi và thứ bạn cần.',
    note: 'Tìm đúng thông tin được nêu. Xem transcript hoặc gợi ý vẫn giúp học; app ghi nhận đó là lượt có hỗ trợ.',
    read: [
      'The class is on Wednesday at nine. There are six students. Please bring a pen and some water.',
      'Có bao nhiêu học viên?',
      ['Ba', 'Sáu', 'Chín'],
      1,
      'Đừng nhầm giờ nine với số học viên.',
      'Six students là sáu học viên.',
    ],
    recall: [
      'Điền is hoặc are: There ___ three bags under the table.',
      'are',
      'Three bags là số nhiều.',
      'There are đi với three bags.',
    ],
    listen: [
      'Go straight. Turn left at the cafe. The school is next to the park.',
      'Cần rẽ trái ở đâu?',
      ['Quán cà phê', 'Ngân hàng', 'Công viên'],
      0,
      'Nghe nơi sau Turn left at.',
      'Turn left at the cafe: rẽ trái ở quán cà phê.',
    ],
    review: [
      'Điền on hoặc at: Our class is ___ Thursday.',
      'on',
      'Thursday là thứ trong tuần.',
      'On Thursday là vào thứ Năm.',
    ],
    speaking: 'Nhờ một việc lịch sự rồi nói một điểm hẹn có giờ.',
    writing: 'Viết lời nhắn gồm nơi, giờ và hai món cần mang.',
    check: ['At/on đúng với giờ/thứ.', 'Danh từ và số lượng phù hợp.', 'Lời nhờ có please.'],
  },
  {
    id: 'week-4-check',
    checkpoint: 4,
    title: 'Nhìn lại bốn tuần',
    topic: 'Học tập',
    goal: 'Phân biệt chuyện đã qua, dự định và lý do trong ngữ cảnh ngắn.',
    phrase: 'Think about yesterday and one plan for tomorrow.',
    translation: 'Nghĩ về hôm qua và một kế hoạch ngày mai.',
    note: 'Đây là điểm dừng để nhìn lại bộ học liệu thử nghiệm. Làm được ba câu không chứng minh đã đạt một trình độ hoặc sẵn sàng thi IELTS.',
    read: [
      'Yesterday, Leo was at home. He cooked lunch because his sister was busy. Tomorrow, he is going to visit her.',
      'Vì sao Leo nấu bữa trưa?',
      ['Chị/em gái bận', 'Leo đi du lịch', 'Quán đóng cửa'],
      0,
      'Chọn lý do được nêu sau because.',
      'Because his sister was busy: vì chị/em gái bận.',
    ],
    recall: [
      'Điền go hoặc went: We did not ___ to the cafe yesterday.',
      'go',
      'Sau did not dùng động từ nguyên dạng.',
      'Did not go là cấu trúc phủ định quá khứ đúng.',
    ],
    listen: [
      'Tomorrow, I am going to meet my friend at the library at five.',
      'Cuộc hẹn dự định vào lúc nào?',
      ['Hôm qua lúc năm giờ', 'Ngày mai lúc năm giờ', 'Ngày mai lúc chín giờ'],
      1,
      'Nghe cả Tomorrow và at five.',
      'Tomorrow và at five xác định ngày mai lúc năm giờ.',
    ],
    review: [
      'Điền một từ: We are going ___ study tomorrow.',
      'to',
      'Mẫu be going to + động từ.',
      'We are going to study tomorrow.',
    ],
    speaking: 'Kể hai câu về hôm qua, rồi nói một kế hoạch và lý do.',
    writing: 'Viết ba hoặc bốn câu: việc đã làm, việc chưa làm, dự định và một lý do.',
    check: [
      'Phân biệt động từ quá khứ với sau did not.',
      'Dự định có be going to.',
      'Because nối một lý do rõ.',
      'Tự chọn một điểm cần luyện thêm.',
    ],
  },
]

const themes = {
  'Đời sống': ['sand', 'sun'],
  'Giải trí': ['mint', 'game'],
  'Ăn uống': ['peach', 'coffee'],
  'Học tập': ['lavender', 'study'],
} as const
function lesson(unit: Unit, day: number): Lesson {
  return {
    id: unit.id,
    day,
    title: unit.title,
    subtitle: unit.goal,
    topic: unit.topic,
    color: themes[unit.topic][0],
    icon: themes[unit.topic][1],
    minutes: 5,
    phrase: unit.phrase,
    translation: unit.translation,
    note: unit.note,
    goal: unit.goal,
    exercises: [
      choice('reading', unit.read),
      recall('recall', unit.recall),
      choice('listening', unit.listen, true),
    ],
    review: recall(`${unit.id}-review`, unit.review),
    reflection: unit.writing,
    speaking: unit.speaking,
    selfCheck: unit.check,
    ...(unit.checkpoint ? { checkpoint: unit.checkpoint } : {}),
  }
}
export const additionalLessons = units.map((unit, index) => lesson(unit, index + 8))
export const weeklyChecks = checkpoints.map((unit, index) => lesson(unit, (index + 1) * 7))
