// Editorial ordering for suggestions, not a mastery model or a lock on Discover.
export const prerequisites: Record<string, readonly string[]> = {
  hello: [],
  friends: ['hello'],
  tea: ['hello'],
  room: ['hello'],
  morning: ['hello'],
  yesterday: ['morning'],
  tonight: ['hello'],
  'week-1-check': ['hello', 'friends', 'tea', 'room', 'morning', 'yesterday', 'tonight'],
  family: ['hello'],
  have: ['family'],
  likes: ['friends', 'family'],
  questions: ['likes'],
  negative: ['questions'],
  ability: ['hello'],
  routine: ['morning', 'likes'],
  'week-2-check': ['family', 'have', 'likes', 'questions', 'negative', 'ability', 'routine'],
  plural: ['have'],
  places: ['room', 'plural'],
  directions: ['places'],
  shopping: ['tea', 'plural'],
  prices: ['shopping'],
  schedule: ['morning'],
  requests: ['ability', 'tea'],
  'week-3-check': ['plural', 'places', 'directions', 'shopping', 'prices', 'schedule', 'requests'],
  'past-be': ['family'],
  'past-actions': ['yesterday'],
  'past-negative': ['past-actions', 'negative'],
  'future-plans': ['tonight'],
  reasons: ['likes'],
  messages: ['schedule', 'requests'],
  'small-story': ['past-be', 'past-actions', 'future-plans', 'reasons'],
  'week-4-check': [
    'past-be',
    'past-actions',
    'past-negative',
    'future-plans',
    'reasons',
    'messages',
    'small-story',
  ],
}
